// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSPRFlEoiurZ5iSHGUzvkG2syNQXTHUkQ',
    appId: '1:129113007184:web:30eb920e0b4b0d3b6b5d55',
    messagingSenderId: '129113007184',
    projectId: 'authentication-test-202be',
    authDomain: 'authentication-test-202be.firebaseapp.com',
    storageBucket: 'authentication-test-202be.firebasestorage.app',
    measurementId: 'G-0G5HXY5V23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvKJiQ2Tbz_KzbXiL8OeU6gSjZJhuWoC8',
    appId: '1:129113007184:android:875435da9ec6c2fb6b5d55',
    messagingSenderId: '129113007184',
    projectId: 'authentication-test-202be',
    storageBucket: 'authentication-test-202be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKtPxPlffgKmB4a9AZNq60T1j_16EuCAc',
    appId: '1:129113007184:ios:b02a920d5bb7d5686b5d55',
    messagingSenderId: '129113007184',
    projectId: 'authentication-test-202be',
    storageBucket: 'authentication-test-202be.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKtPxPlffgKmB4a9AZNq60T1j_16EuCAc',
    appId: '1:129113007184:ios:b02a920d5bb7d5686b5d55',
    messagingSenderId: '129113007184',
    projectId: 'authentication-test-202be',
    storageBucket: 'authentication-test-202be.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSPRFlEoiurZ5iSHGUzvkG2syNQXTHUkQ',
    appId: '1:129113007184:web:4df94d53108e22e76b5d55',
    messagingSenderId: '129113007184',
    projectId: 'authentication-test-202be',
    authDomain: 'authentication-test-202be.firebaseapp.com',
    storageBucket: 'authentication-test-202be.firebasestorage.app',
    measurementId: 'G-QZVEGBHJPT',
  );
}
